### ISSUE TITLE
Widget dynamic size

### ISSUE THREAD

**Issue by Fred-Vatin** [mattbierner/vscode-color-info#10]
Very nice and useful. 

Just one thing: the color info panel (widget) has a scrollbar because it is too small in height to display all the fields. Couldn't be there a way to make the panel size dynamic (auto height according to content) so it gets the needed size according to fields it has to show? Or provide a user setting to fix the size?

**Comment by mattbierner** [comment]
Thanks for the suggestion. Unfortunately this is not something that extensions can really control. VSCode determines the size of the hover widget and scrollbars are added if the content is larger than the widget size
