### ISSUE TITLE
Doesn't work with js files

### ISSUE THREAD

**Issue by di9it** [mattbierner/vscode-color-info#12]
- Extension Name: color-info
- Extension Version: 0.5.0
- OS Version: Darwin x64 17.4.0
- VSCode version: 1.19.2

 We have written the needed data into your clipboard. Please paste:
```json 
{
	"activationTimes": {
		"startup": true,
		"codeLoadingTime": 123,
		"activateCallTime": 1,
		"activateResolvedTime": 0,
		"activationEvent": "*"
	}
}
```

Added
        {
            "selector": "js",
            "colors": "css"
        }

**Comment by zdrummond** [comment]
I think the selector should actually be `javascript` like 

```
{
      "selector": "javascript",
      "colors": "css"
}
```

But it still does not work

**Comment by mattbierner** [comment]
Yes, it should be:

```json
 {
            "selector": "javascript",
            "colors": "css"
},{
            "selector": "javascriptreact",
            "colors": "css"
}
```

<img width="593" alt="screen shot 2018-03-03 at 12 46 02 pm" src="https://user-images.githubusercontent.com/212305/36939130-d9d0cef2-1ee0-11e8-92b2-b4316bf2c534.png">

The babel and flow extensions also register their own language modes so you'll need to adjust the selectors accordingly

**Comment by zdrummond** [comment]
Perfect! I had not done the `javascriptreact`, and now it works. 

However, one question. As you show above, and I see in my React code, the color box that normally precedes a color in `css` does not appear in JSX

<img width="353" alt="basestyles_css" src="https://user-images.githubusercontent.com/1627527/36939186-c1855a42-1ee1-11e8-83af-49f9ea41ffd5.png">

Anyone to get that working?
