### ISSUE TITLE
Sass color label

### ISSUE THREAD

**Issue by romanlex** [mattbierner/vscode-color-info#13]
Why In .sass files I doesn't see any color labels?
Example **.scss**
![image](https://user-images.githubusercontent.com/3369304/36798804-a65451dc-1cbc-11e8-9ec4-145542c15e85.png)
Example **.sass**
![image](https://user-images.githubusercontent.com/3369304/36798837-badfc17c-1cbc-11e8-8e94-9959b0e887a5.png)

**Comment by mattbierner** [comment]
Those are color decorators. This extension does not actually provide those, they either come from a vscode built-in extension or through another marketplace extension.  This extension provides color information when you hover over anything that looks like a color (even if it does not have color decorators)
