### ISSUE TITLE
Some colors do not have names

### ISSUE THREAD

**Issue by ethikz** [mattbierner/vscode-color-info#16]
I've changed the configuration to show `css-color-name` but it doesn't show up in the preview for anything other than basic colors like white, black, yellow, red, etc.

The config snippet is:

```
"colorInfo.fields": [
        "css-color-name",
        "hex",
        "rgb",
        "alpha",
        "preview-xl"
    ]
```

This doesn't show the color name
![Screen Shot 2019-03-29 at 10 48 10](https://user-images.githubusercontent.com/1078765/55241098-c172ee80-5210-11e9-9b06-7a80ca5e10c2.png)

This shows basic color name
![Screen Shot 2019-03-29 at 10 52 43](https://user-images.githubusercontent.com/1078765/55241132-d64f8200-5210-11e9-8bf5-0c055b7793af.png)

Is this a bug or is it not meant to give names to all colors?

**Comment by mattbierner** [comment]
It only shows the css name if there is a matching one. As far as I know, there is no named color for `#232ff5`

**Comment by ethikz** [comment]
There are others that will say it's `blue` or for instance, for that color I've even seen `Han Purple` for the exact hex `#232ff5`
