### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by RodneyMakundi** [mattbierner/vscode-color-info#17]
- Issue Type: `Performance`
- Extension Name: `color-info`
- Extension Version: `0.5.1`
- OS Version: `Windows_NT x64 6.3.9600`
- VSCode version: `1.32.3`

:warning: Make sure to **attach** this file from your *home*-directory: `C:\Users\pc\bierner.color-info-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by mattbierner** [comment]
You need to attach the profile as instructed. See the link for details

**Comment by mattbierner** [comment]
Closing as more info is needed to investigate
