### ISSUE TITLE
Not an issue - 

### ISSUE THREAD

**Issue by johndpope** [mattbierner/vscode-color-info#18]
I created this git issue suggesting to upgrade the intellisense with a force directed layout.
https://github.com/MicrosoftDocs/intellicode/issues/123

It seems the vscode.HoverProvider that you've configured would help me prototype idea - 
But I wonder if there's a more accurate place to start as it's really around the auto completion and how this data hooks together that I want to hack into a force directed layout.

open to collaboration if there's interest.

**Comment by mattbierner** [comment]
Closing as this doesn't seem related to this repo
