### ISSUE TITLE
support .vue file

### ISSUE THREAD

**Issue by tjx666** [mattbierner/vscode-color-info#19]
This extension is awesome! 
But vue.js is my daily front end framework, and it doesn't use a separated style file, this extension doesn' t work in style tag of  .vue file.

**Comment by mattbierner** [comment]
Have you tried configuring the plugin to be enabled for Vue files: https://github.com/mattbierner/vscode-color-info#colorinfolanguages

**Comment by tjx666** [comment]
ok, that can solve by configuring the plugin. @mattbierner
