### ISSUE TITLE
Ability to specify file extensions

### ISSUE THREAD

**Issue by Avol-V** [mattbierner/vscode-color-info#2]
It would be cool, if you add a setting to specify file extensions to work with. It can help with some exotic files (or not so exotic, like pcss).

**Comment by mattbierner** [comment]
I just publish 0.2 that adds a [`colorInfo.languages` setting](https://github.com/mattbierner/vscode-color-info#colorinfolanguages) that enables this. You should be able to now use Color Info for whatever files / languages you like, and also control what format of colors supported for each. 

Please let me know if you have any questions or run into any issues.

Thanks
