### ISSUE TITLE
Support for css module values

### ISSUE THREAD

**Issue by GreenGremlin** [mattbierner/vscode-color-info#20]
Using [postcss-modules-values](https://github.com/css-modules/postcss-modules-values) colors can be shared using a property.

```css
@value carbon: #7b7789;
```

It would be nice if the color info extension supported this type of property definition.

**Comment by mattbierner** [comment]
Do you mean displaying the color when you hover over references to `carbon`?

**Comment by GreenGremlin** [comment]
That would be cool, but at least the definition would be nice

**Comment by mattbierner** [comment]
What is the language mode is the file? This should already work as long as you enable this extension for your language: https://github.com/mattbierner/vscode-color-info#colorinfolanguages

**Comment by mattbierner** [comment]
Closing as this should work with the correct configuration
