### ISSUE TITLE
Update extensionKind

### ISSUE THREAD

**Issue by bamurtaugh** [mattbierner/vscode-color-info#25]
Hey @mattbierner! 

I noticed this extension has the `extensionKind` set to `["ui"]`: https://github.com/mattbierner/vscode-color-info/blob/master/package.json#L8, which defines it can only run in the VS Code desktop extension host. 

However, I think it's also suitable to be run on the workspace extension host, and it'd make sense to update `extensionKind` to `["ui", "workspace"]`.

Please let me know if this sounds reasonable, or if there might be a reason this should remain a strict UI extension. Thank you!

**Comment by mattbierner** [comment]
Yep that makes sense. Would you like to submit a quick PR that makes this change?

**Comment by bamurtaugh** [comment]
Just submitted https://github.com/mattbierner/vscode-color-info/pull/26!
