### ISSUE TITLE
Inline style support

### ISSUE THREAD

**Issue by keithstric** [mattbierner/vscode-color-info#3]
If in a .html file with an inline style block. The color info is not showing.

**Comment by mattbierner** [comment]
The story for nested languages in VSCode is still not great, but I just publish 0.2 that adds a [`colorInfo.languages` setting](https://github.com/mattbierner/vscode-color-info#colorinfolanguages) that enables this. With this setting, you can control what file types have color info enabled. To enable color info for inline css inside of html files, you would set: 

```
"colorInfo.languages": [
    { "selector": "css", "colors": "css" },
    { "selector": "sass", "colors": "css" },
    { "selector": "less", "colors": "css" },
    { "selector": "html", "colors": "css" }  
}
```

The last line is the extra setting you need to add. By default, color info is only enabled for css type documents.

Adding a setting for `html` makes color Info try to extract css style colors inside html documents, enabling color information for both `<style>` tags and inline styles. There may be false positive color matches however. You can use the same setting to enable color info for css colors inside of JS/react or other funky languages

Give it a try and let me know if you run into any problems. 

Thanks

**Comment by keithstric** [comment]
Sorry it took me a while to get back to this. I updated and enabled the settings you mentioned but still not seeing the color info inside an html file. My style block looks like this if it matters:

```
<style is="custom-style" include="iron-flex iron-flex-alignment dig-shared-styles">

	:root {
		--dark-primary-color: #8f2a24;
		--default-primary-color: #c33931;
		--primary-color: #c33931;
		--light-primary-color: #cc9999;
		--text-primary-color: #ffffff;
		--accent-color: #f5c300;
		--primary-text-color: #212121;
		--secondary-text-color: #727272;
		--divider-color: #b6b6b6;
		--body-background-color: #727272;
	}

</style>
```

I know that's a bit different with the CSS Variables and wasn't sure if maybe that may be the problem. Wow, the formatting of that code really sucks.

**Comment by mattbierner** [comment]
I know it's not terribly helpful, but I do see this working on VSCode 1.8 with ColorInfo 0.2.0:

![dec-17-2016 00-21-54](https://cloud.githubusercontent.com/assets/212305/21285487/de2c2206-c3ee-11e6-8a36-24b805541cda.gif)

Can you share the exact setting for `colorInfo.language`, along with the entire html file if possible (or a minimal html file that reproduces this).

Thanks

**Comment by keithstric** [comment]
Here's my colorInfo.language:
`"colorInfo.languages": [
            {"selector": "css","colors": "css"},
            {"selector": "sass","colors": "css"},
            {"selector": "less","colors": "css"},
            {"selector": "html","colors": "css"}
        ]`

Here's the app-theme.html file.
[https://jsfiddle.net/keithstric/vbub6nzj/3/](url)

**Comment by mattbierner** [comment]
@keithstric Still seeing things working properly on a mac and on windows using those exact settings and that exact file. What other extensions do you have installed?

**Comment by keithstric** [comment]
![screen shot 2016-12-18 at 10 31 14 am](https://cloud.githubusercontent.com/assets/463194/21294550/32b4fce8-c50d-11e6-8fba-2a333c11f858.png)

Now that I think about it. The file type of html files is Polymer. Could that have something to do with the issue?

![screen shot 2016-12-18 at 10 34 09 am](https://cloud.githubusercontent.com/assets/463194/21294568/94eccd50-c50d-11e6-9335-bc56df3c66e4.png)

**Comment by keithstric** [comment]
I apologize for the delay in pursuing this, but just a quick update. Installed latest version and changed this in my settings:
"colorInfo.languages": [
            {"selector": "css","colors": "css"},
            {"selector": "sass","colors": "css"},
            {"selector": "less","colors": "css"},
            {"selector": "html","colors": "css"},
            {"selector": "polymer","colors": "css"}
        ]

Adding the "polymer" language to the settings fixed this issue. Thank you for taking the time to try and help.
