### ISSUE TITLE
HSL(a) colors get no preview square

### ISSUE THREAD

**Issue by melcarthus** [mattbierner/vscode-color-info#34]
While hovering over a HSL color works, I get no colored square in front of the variable or written hsl color in SASS.
I'm on a M1 Max Pro with Version: 1.71.2 (Universal)

Version: 1.71.2 (Universal)
Commit: 74b1f979648cc44d385a2286793c226e611f59e7
Date: 2022-09-14T21:05:37.721Z (2 wks ago)
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 21.6.0
Sandboxed: No

**Comment by theking2** [comment]
![image](https://user-images.githubusercontent.com/1612152/212468715-9b6dc591-0666-4846-a452-f75660a1d40d.png)

**Comment by mattbierner** [comment]
This extension only provides the hover information. The color squares are either provided by vscode itself, or by other extensions. Please file issues against them for detecting `hsl` colors
