### ISSUE TITLE
FR: Show "name" for named colors

### ISSUE THREAD

**Issue by Olian04** [mattbierner/vscode-color-info#4]
Could you add an option to show the name of a color if the current color matches (or is close to) any of the standard named colors in CSS. 

Ex: The color hexa `#3cb371` would show the text `mediumseagreen` and the color hexa `ff4500` would show the text `orangered`.

**Comment by mattbierner** [comment]
Added using `css-color-name` field in 0.3.0. Just add the display with a setting like `"colorInfo.fields": ["css-color-name", "rgb", "hex", ...]` since it's not enabled by default
