### ISSUE TITLE
Add scss file extension to default languages

### ISSUE THREAD

**Issue by CedarDCX** [mattbierner/vscode-color-info#5]
Howdy! Good work on this extension!

It says in the documentation "by default, the extension works with any css, sass, or less document", except it doesn't seem to work with .scss files out of the box. Adding the following to `colorInfo.languages` seemed to fix it:

`{
    "selector": "scss",
    "colors": "css"
}`

Perhaps this should be added as default?

**Comment by smlombardi** [comment]
Yes, most of us use scss not sass.

**Comment by mattbierner** [comment]
I may not be able to get around to this, so feel free to submit a PR with the fix and I'll publish an update to the extension

**Comment by mattbierner** [comment]
Fixed by  @smlombardi with #7

Just published 0.4 with the change
