### ISSUE TITLE
Recognize colors enclosed within quotes

### ISSUE THREAD

**Issue by exists-forall** [mattbierner/vscode-color-info#8]
In languages like Elm where CSS is frequently constructed and represented using strings, it is common to enclose CSS colors in string literals, like `"#AABBCC"`.  Color-Info seems not to recognize these as colors, unless there is a space in the string like `" #AABBCC"`.

**Comment by mattbierner** [comment]
Thanks for the report. Just published 0.4.1 which should fix this
